In [7]:
import numpy as np

In [8]:
x=np.array([1,2,3,4])
print(x)
print(type(x))


[1 2 3 4]
<class 'numpy.ndarray'>


In [9]:
import numpy as np
print(np.__version__)

1.26.3


In [22]:
# %%timeit :It is an important function that tells us how much time is consume to make a list or arrays

In [12]:
%timeit [j**4 for j in range(1,10)]

2.52 µs ± 290 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


# NumPy Creating Arrays

In [3]:
import numpy as np
x=np.array([1,2,3])
print(x)
print(x.ndim)

[1 2 3]
1


In [17]:
y=[2,3,4,5]
y=np.array(y)
print(y)
y

[2 3 4 5]


array([2, 3, 4, 5])

# Taking array as input from user

In [2]:
import numpy as np
list=[]
for i in range(1,5):
    ele=int(input("Enter elements:"))
    list.append(ele)
    
print(np.array(list))


Enter elements: 1
Enter elements: 2
Enter elements: 3
Enter elements: 4


[1 2 3 4]


# 2D arrays

In [5]:
import numpy as np
x=np.array([[1,2,3,4],[1,2,3,4]])
print(x)
print(x.ndim)

[[1 2 3 4]
 [1 2 3 4]]
2


# 3D arrays

In [7]:
import numpy as np
x=np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
print(x)
print(x.ndim)

[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]
3


# Creating N/multi-dimensions arrays

In [10]:
arr=np.array([1,2,3],ndmin=10)
print(arr)
print(arr.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]]
10


In [5]:
import numpy as np
y=np.array(2)
print(y)
print(y.ndim)
print(y.shape)

2
0
()


# Zeroes

In [2]:
import numpy as np

In [4]:
ar_zeros=np.zeros(4)
print(ar_zeros)

[0. 0. 0. 0.]


In [5]:
# To create 2D array with all elements zeros.
ar_zeros1=np.zeros((2,2))
print(ar_zeros1)

[[0. 0.]
 [0. 0.]]


In [6]:
# To create 2D array with all elements zeros.
ar_zeros1=np.zeros((3,2))
print(ar_zeros1)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


# Ones

In [7]:
arr_ones=np.ones(4)
print(arr_ones)

[1. 1. 1. 1.]


In [8]:
#To create 2D array with all elements ones. 
arr_ones1=np.ones((2,3))
print(arr_ones1)

[[1. 1. 1.]
 [1. 1. 1.]]


# Empty

In [3]:
arr_em=np.empty(4)
print(arr_em)

[0.00000000e+000 1.56870079e-311 1.56870079e-311 1.56870079e-311]


# Range

In [11]:
arr_range=np.arange(4)
print(arr_range)

[0 1 2 3]


# Identity Matrixs

In [17]:
arr_iden=np.identity(3)
print(arr_iden)

arr_iden=np.eye(2)
print(arr_iden)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0.]
 [0. 1.]]


# Linespace

In [18]:
arr_lin=np.linspace(0,20,5)
print(arr_lin)

[ 0.  5. 10. 15. 20.]


# Random

# rand

In [20]:
import numpy as np

In [22]:
var=np.random.rand(4)
print(var)

[0.57205126 0.47456812 0.2314169  0.73821286]


In [23]:
# To create 2d array
var1=np.random.rand(2,2)
print(var1)

[[0.52350357 0.50720346]
 [0.47685944 0.76631377]]


# Randn()

In [29]:
var_ran=np.random.randn(4)
print(var_ran)

[-0.90314623  0.63109362 -0.28149781 -1.31443763]


# Ranf()

In [31]:
var3=np.random.ranf(4)
print(var3)

[0.42441232 0.83369153 0.53100732 0.93437119]


# Randint()

In [32]:
# var4=np.random.randint(min,max,total_value)
var4=np.random.randint(0,5,5)
print(var4)

[0 2 0 3 1]


In [33]:
var4=np.random.randint(0,5,6)
print(var4)

[2 2 1 0 2 0]


# Datatype

In [34]:
import numpy as np

In [36]:
a=np.array([1,2,3,4])
print("Datatype:",a.dtype)

Datatype: int32


In [37]:
a=np.array([1,2,3.4])
print("Datatype:",a.dtype)

Datatype: float64


In [38]:
a=np.array(["ansh","rehan"])
print("Datatype:",a.dtype)

Datatype: <U5


In [39]:
a=np.array([1,2,"s"])
print("Datatype:",a.dtype)

Datatype: <U11


In [40]:
# Convert Datatype
# Convert int32 into int8

In [45]:
x=np.array([1,2,3,4],dtype=np.int8)
print("Dataype:",x.dtype)

Dataype: int8


In [46]:
# Convert int datatype into float

In [47]:
x=np.array([1,2,3,4],dtype="f")
print("Dataype:",x.dtype)

Dataype: float32


In [48]:
# Convert dataypes as a functions/

In [52]:
x1=np.array([1,2,3])
new=np.float32(x1)
print("Datatype: ",x1.dtype)
print("Datatype: ",new.dtype)
print(x)
print(new)

Datatype:  int32
Datatype:  float32
[1. 2. 3. 4.]
[1. 2. 3.]


# Arithmetic operations in array

In [2]:
import numpy as np

In [3]:
arr1=np.array([1,2,3])
var_add=arr1+3
print(var_add)

[4 5 6]


In [10]:
# Using numpy functions.
arr1=np.array([1,2,3])
arr2=np.array([1,2,3])
var_add=np.add(arr1,arr2)
print(var_add)

[2 4 6]


In [4]:
arr1=np.array([1,2,3])
arr2=np.array([1,2,3])
var_add=arr1+arr2
print(var_add)

[2 4 6]


In [5]:
arr1=np.array([1,2,3])
var_diff=arr1-3
print(var_diff)

[-2 -1  0]


In [13]:
arr1=np.array([1,2,3])
arr2=np.array([1,2,3])
var_add=np.subtract(arr1,arr2)
print(var_add)

[0 0 0]


In [6]:
arr1=np.array([1,2,3])
var_mul=arr1*3
print(var_mul)

[3 6 9]


In [7]:
arr1=np.array([1,2,3])
var_mod=arr1%3
print(var_mod)

[1 2 0]


In [8]:
arr1=np.array([1,2,3])
var_div=arr1/3
print(var_div)

[0.33333333 0.66666667 1.        ]


# 2D array

In [20]:
arr21=np.array([[1,2,3],[1,2,3]])
arr22=np.array([[1,2,3],[2,3,4]])
var_add=arr21+arr22
print(var_add)

[[2 4 6]
 [3 5 7]]


# Arithmetic Functions in NumPy Arrays

In [35]:
var1=np.array([1,2,34,4])
print("Min:",np.min(var1))
print("Max:",np.max(var1))
print("sqrt",np.sqrt(var1))

Min: 1
Max: 34
sqrt [1.         1.41421356 5.83095189 2.        ]


In [26]:
print("Position of min:",np.argmin(var1))
print("Position of max:",np.argmax(var1))

Position of min: 0
Position of max: 2


In [31]:
var2=np.array([[1,2,4],[6,7,0]])
print(np.min(var2,axis=1))

[1 0]


In [32]:
var2=np.array([[1,2,4],[6,7,0]])
print(np.min(var2,axis=0))

[1 2 0]


In [38]:
var2=np.array([1,2,3])
print("Sin:",np.sin(var2))
print("Cos:",np.cos(var2))

Sin: [0.84147098 0.90929743 0.14112001]
Cos: [ 0.54030231 -0.41614684 -0.9899925 ]


In [39]:
print("Cumsum :",np.cumsum(var2))

Cumsum : [1 3 6]


# Shape

In [43]:
var=np.array([[1,2,3],[1,2,3]])
print(var)
print()
print(np.shape(var))

[[1 2 3]
 [1 2 3]]

(2, 3)


In [47]:
var=np.array([1,2,3,4],ndmin=10)
print(np.shape(var))

(1, 1, 1, 1, 1, 1, 1, 1, 1, 4)


# Reshape

In [58]:
var=np.array([1,2,3,4,5,6,7,8])
print(var.reshape(2,4))
x=var.reshape(2,4)
print("Dim",x.ndim)

[[1 2 3 4]
 [5 6 7 8]]
Dim 2


In [56]:
print("Shape",np.shape(var))

Shape (8,)


In [57]:
print("Dim",var.ndim)

Dim 1


In [13]:
var=np.array([1,2,3,99,9,5,6,7,8])
print(np.sort(var))

[ 1  2  3  5  6  7  8  9 99]


# Indexing

In [1]:
import numpy as np
var=np.array([1,2,3,4,5])
print(var)

[1 2 3 4 5]


In [5]:
print(var[0])
print(var[4])
print(var[-2])

1
5
4


In [10]:
var1=np.array([[1,2,3],[4,5,6]])
print(var1)
print()
print(var1[0][1])
print(var1[0,1])

[[1 2 3]
 [4 5 6]]

2
2


In [13]:
var2=np.array([[[1,2,3],[4,5,6]]])
print(var2)
print()
print(var2[0,0,1])

[[[1 2 3]
  [4 5 6]]]

2


# Slicing

In [16]:
var=np.array([1,2,3,4,5,6])
print(var[0:3:1])

[1 2 3]


In [19]:
print(var[::-1])

[6 5 4 3 2 1]


In [20]:
print(var[:6])

[1 2 3 4 5 6]


# Iterating

In [22]:
var=np.array([1,2,3,4,5,6,7,8,9])
for i in var:
    print(i,end=" ")

1 2 3 4 5 6 7 8 9 

In [31]:
var1=np.array([[1,2,3],[4,5,6]])
for i in var1:
    
    # for j in var1:
    print(i)
# print(var.ndim)

for j in var1:
    for k in j:
        print(k,end=" ")

[1 2 3]
[4 5 6]
1 2 3 4 5 6 

In [33]:
# For 3D array
var2=np.array([[[1,2,3,4],[5,6,7,8]]])
print(var2)
print(var2.ndim)
for i in var2:
    for j in i:
        for k in j:
            print(k,end =" ") 

[[[1 2 3 4]
  [5 6 7 8]]]
3
1 2 3 4 5 6 7 8 

# np.nditer()

In [ ]:
# nditer(var): It is used to iterate for big array by not using complex loops.

In [35]:
var2=np.array([[[1,2,3,4],[5,6,7,8]]])
for i in np.nditer(var2):
    print(i)

1
2
3
4
5
6
7
8


In [36]:
# np.ndenumerate(var) :It gives the data and index of that data from the array.

In [38]:
var2=np.array([[[1,2,3,4],[5,6,7,8]]])
for i,d in np.ndenumerate(var2):
    print(i,d)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 1, 0) 5
(0, 1, 1) 6
(0, 1, 2) 7
(0, 1, 3) 8


# Copy vs View

In [52]:
var=np.array([1,2,3])

co=var.copy()
var[0]=10
print("Var:",var)
print("Copy:",co)


Var: [10  2  3]
Copy: [1 2 3]


In [53]:
a=np.array([9,8,7,6])
b=a.view()
a[0]=10
print("Var:",a)
print("View",b)

Var: [10  8  7  6]
View [10  8  7  6]


# Join Array

In [60]:
var1=np.array([1,2,3,4])
var2=np.array([5,6,7,8])
arr=np.concatenate((var1,var2))
print(arr)

[1 2 3 4 5 6 7 8]


In [81]:
var1=np.array([1,2,3,4])
var2=np.array([5,6,7,8])
c=np.vstack((var1,var2))  #colums
d=np.hstack((var1,var2))  #rows
e=np.hstack((var1,var2)) #heigth
print()
print(c)
print()
print(d)
print()
print(e)


[[1 2 3 4]
 [5 6 7 8]]

[1 2 3 4 5 6 7 8]

[1 2 3 4 5 6 7 8]


In [67]:
var3=np.array([[1,2,3],[4,5,6]])
var4=np.array([[7,8,9],[0,9,8]])
arr1=np.concatenate((var3,var4))
arr2=np.concatenate((var3,var4),axis=1)
arr3=np.concatenate((var3,var4),axis=0)
print(arr1)
print()
print(arr2)
print()
print(arr3)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [0 9 8]]

[[1 2 3 7 8 9]
 [4 5 6 0 9 8]]

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [0 9 8]]


In [68]:
# np.stack()

In [70]:
var3=np.array([[1,2,3],[4,5,6]])
var4=np.array([[7,8,9],[0,9,8]])
x=np.stack((var3,var4))
print(x)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [0 9 8]]]


In [73]:
var3=np.array([[1,2,3],[4,5,6]])
var4=np.array([[7,8,9],[0,9,8]])
x=np.vstack((var3,var4))
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [0 9 8]]


In [74]:
var3=np.array([[1,2,3],[4,5,6]])
var4=np.array([[7,8,9],[0,9,8]])
x=np.hstack((var3,var4))
print(x)

[[1 2 3 7 8 9]
 [4 5 6 0 9 8]]
